---
- hosts: devbox
  vars:
    username: yevgeny
    dotfiles_repo: https://github.com/yevgenybulochnik/dotfiles.git
    install_dotfiles: True
    PPAS:
      - ppa:jonathonf/vim
      - ppa:ansible/ansible
    packages:
      - vim
      - ansible
      - htop
    domain: yevgenybulochnik.com
    ssl_cert: self_signed
    web_pass: $apr1$X58cIV88$onWdoj/JHuCNc8Ml/FyKd/
  roles:
    - setup_packages
    - setup_user
    - gotty
    - apache
    - fail2ban
    - pyenv
