- name: Install Postgres
  apt:
    name: "{{ postgres_deps}}"
    state: latest
    update_cache: yes
  vars:
    postgres_deps:
      - postgresql
      - postgresql-contrib
      - libpq-dev

- name: Install psycopg2
  pip:
    name: psycopg2

- name: Set postgres user password
  postgresql_user:
    db: postgres
    user: postgres
    password: "postgres"
  become: True
  become_user: postgres
